annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 10.9.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - owncloud-database
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: ownCloud is an open source content collaboration platform used to store and share files from any device. It grants data privacy, synchronization between devices, and file access control.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/owncloud
icon: https://bitnami.com/assets/stacks/owncloud/img/owncloud-stack-220x234.png
keywords:
  - owncloud
  - storage
  - http
  - web
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: owncloud
sources:
  - https://github.com/bitnami/bitnami-docker-owncloud
  - https://owncloud.org/
version: 11.0.20
