annotations:
  category: CRM
apiVersion: v2
appVersion: 7.12.5
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: SuiteCRM is a completely open source, enterprise-grade Customer Relationship Management (CRM) application. SuiteCRM is a fork of the popular SugarCRM application.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/suitecrm
icon: https://bitnami.com/assets/stacks/suitecrm/img/suitecrm-stack-220x234.png
keywords:
  - suitecrm
  - crm
  - http
  - web
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: suitecrm
sources:
  - https://github.com/bitnami/bitnami-docker-suitecrm
  - https://www.suitecrm.com/
version: 10.0.17
