# Test values file for generating all of the yaml and check that
# the rendering is correct
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: sonarqube.local
volumePermissions:
  enabled: true
metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
