# Test values file for generating all of the yaml and check that
# the rendering is correct
locator:
  service:
    type: ClusterIP
ingress:
  enabled: true
  hostname: geode.local
volumePermissions:
  enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
