# Test values file for generating all of the yaml and check that
# the rendering is correct
ingress:
  enabled: true
  tls: true
  selfSigned: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
