annotations:
  category: CMS
apiVersion: v2
appVersion: 8.0.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - osclass-database
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Osclass allows you to easily create a classifieds site without any technical knowledge. It provides support for presenting general ads or specialized ads, is customizable, extensible and multilingual.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/osclass
icon: https://bitnami.com/assets/stacks/osclass/img/osclass-stack-220x234.png
keywords:
  - osclass
  - classifieds
  - http
  - web
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: osclass
sources:
  - https://github.com/bitnami/bitnami-docker-osclass
  - https://osclass.org/
version: 13.0.19
