annotations:
  category: CMS
apiVersion: v2
appVersion: 5.9.2
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.x.x
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: WordPress for Intel is the most popular blogging application combined with cryptography acceleration for 3rd gen Xeon Scalable Processors (Ice Lake) to get a breakthrough performance improvement.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/wordpress-intel
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - application
  - blog
  - cms
  - http
  - php
  - web
  - wordpress
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wordpress-intel
sources:
  - https://github.com/bitnami/bitnami-docker-wordpress-intel
  - https://wordpress.org/
version: 0.1.24
