annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 9.3.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: SonarQube is an open source quality management platform that analyzes and measures code's technical quality. It enables developers to detect code issues, vulnerabilities, and bugs in early stages.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/sonarqube
icon: https://bitnami.com/assets/stacks/sonarqube/img/sonarqube-stack-220x234.png
keywords:
  - sonarqube
  - code-quality
  - code-review
  - static-analysis
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: sonarqube
sources:
  - https://github.com/bitnami/bitnami-docker-sonarqube
  - https://github.com/SonarSource/sonarqube
version: 1.0.6
