annotations:
  category: Wiki
apiVersion: v2
appVersion: 1.37.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mediawiki-database
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: MediaWiki is the free and open source wiki software that powers Wikipedia. Used by thousands of organizations, it is extremely powerful, scalable software and a feature-rich wiki implementation.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/mediawiki
icon: https://bitnami.com/assets/stacks/mediawiki/img/mediawiki-stack-220x234.png
keywords:
  - mediawiki
  - wiki
  - http
  - web
  - application
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: mediawiki
sources:
  - https://github.com/bitnami/bitnami-docker-mediawiki
  - https://www.mediawiki.org/
version: 13.0.15
